[[MAGMA]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d241b3b506fa4e96257c01bd44248d169d162932"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "a67377ab87a7db6e8d2ee5433fdbbb3bef5b4a8e8b8dea96c176f93a0bd8430f"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "jetson"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80820594c0a9150b4cd81062f3035d815dfea93e"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "a07b37a4e218c0b74d0a604ca43059853ad931294ca68baa19234040a05bba7e"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+12.8-cuda_platform+jetson.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "12.8"
cuda_platform = "sbsa"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ccb81a9d43dd24fa873f463c05194ae93752a18"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "9d3fdcb7658a885cf92782509a149d6dee0999f96d2f10cadcc796c03471a309"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+12.8-cuda_platform+sbsa.tar.gz"
[[MAGMA]]
arch = "x86_64"
cuda = "12.9"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0446b82b3edb8cfd0a07fc7c39620d6ec2a67114"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "87812cfe9120b97e510d6a533f0059bf99f2661af29a1d6451a05073ec721c8d"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.x86_64-linux-gnu-cxx11-cuda+12.9.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "12.9"
cuda_platform = "jetson"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd4d424a951308c361e4a9d0255f55efc848782f"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "ec7c6fa2cb5dddf7bc6f62a97ffd4eeff1a8008919933c5b3de8977dd47a19f5"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+12.9-cuda_platform+jetson.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "12.9"
cuda_platform = "sbsa"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bae363c96df82e3ca9b94d56fa98582723fb85e"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "bcd4d0135ab12bf70215d874b26f5446b22a192b5a51ece1070ae9f8a2edcf26"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+12.9-cuda_platform+sbsa.tar.gz"
[[MAGMA]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a3faf527b2ef85eda4294552ff91cd22e8605ae"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "54d09635bb8b7b171cc2c3aedea6c4d3737982989a3effcac389fabd58095af7"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef7e6149cd58a4621be4ad73bb98541edacd444b"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "b665e50a0375db7523c38c3d0cf38eb743b801f43f19807582b05cb59025f587"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+13.0.tar.gz"
[[MAGMA]]
arch = "x86_64"
cuda = "13.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "916bbfd6b9b16fddbb0c0a2e36aad8f5f8ce8d9c"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "62c5f2ca4d6018857510fb3f3d844966f2aa87b6f9bee94c8c6e848f888a86a0"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.x86_64-linux-gnu-cxx11-cuda+13.1.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "13.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b45c2c6136b44d55792c784b14874a536b07fa6"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "f4299c4074ce4207948a19c45efe27e2fa6c72ddc993dff43286f5426fcb24a7"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+13.1.tar.gz"
[[MAGMA]]
arch = "x86_64"
cuda = "13.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81cadc24b938dee58547fc68846196dc3fc700ba"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "8a9319cd10dd6e9d6f538887413ea6aff5a61584465897f8e061ca0c1eed3920"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.x86_64-linux-gnu-cxx11-cuda+13.2.tar.gz"
[[MAGMA]]
arch = "aarch64"
cuda = "13.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50e5d4d98781f65e869d4f549f1501f28be72244"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "3be628cd7ab294646043aade691103c82ebbeab50d7a33beefb9636e7745e041"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.10.0+0/MAGMA.v2.10.0.aarch64-linux-gnu-cxx11-cuda+13.2.tar.gz"
