[[MAGMA]]
arch = "x86_64"
cuda = "11.3"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cfad75723348060efed060db0ada2dec4554922"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "0f81eba26fa3e200182acef8e40e430ca9b5ec66673de12beeb0298fac3a0111"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.7.0+1/MAGMA.v2.7.0.x86_64-linux-gnu-cxx03-cuda+11.3.tar.gz"
[[MAGMA]]
arch = "x86_64"
cuda = "11.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dfb31757cdc81f3431df8f9a748c251b3d3638d"
libc = "glibc"
os = "linux"

    [[MAGMA.download]]
    sha256 = "a590b36db4bc8956fa5e3960dd4d42108c31efceb67a2368bbeac13ac2bfd3d6"
    url = "https://github.com/JuliaBinaryWrappers/MAGMA_jll.jl/releases/download/MAGMA-v2.7.0+1/MAGMA.v2.7.0.x86_64-linux-gnu-cxx11-cuda+11.3.tar.gz"
