# Autogenerated wrapper script for MAGMA_jll for aarch64-linux-gnu-cxx11-cuda+12.6-cuda_platform+sbsa
export libmagma, libmagma_sparse

using libblastrampoline_jll
using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("MAGMA")
JLLWrappers.@declare_library_product(libmagma, "libmagma.so")
JLLWrappers.@declare_library_product(libmagma_sparse, "libmagma_sparse.so")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libmagma,
        "lib/libmagma.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libmagma_sparse,
        "lib/libmagma_sparse.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
