# Autogenerated wrapper script for MAGMA_jll for x86_64-linux-gnu-cxx03-cuda+11.3
export libmagma, libmagma_sparse

using CUDA_Runtime_jll
using libblastrampoline_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("MAGMA")
JLLWrappers.@declare_library_product(libmagma, "libmagma.so")
JLLWrappers.@declare_library_product(libmagma_sparse, "libmagma_sparse.so")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Runtime_jll, libblastrampoline_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmagma,
        "lib/libmagma.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libmagma_sparse,
        "lib/libmagma_sparse.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
